### ISSUE TITLE
[SL-2323] [Feature] Update `dbt-metricflow` dependencies to use `dbt-*` 1.8 packages

### ISSUE THREAD

**Issue by plypaul** [dbt-labs/metricflow#1243]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The `dbt-metricflow` package currently depends on `dbt-*` 1.7 packages. Since 1.8 is out, the dependencies should be updated.

<sub>[SL-2323](https://linear.app/dbt-labs/issue/SL-2323/[feature]-update-dbt-metricflow-dependencies-to-use-dbt-18-packages)</sub>

**Comment by adamcunnington-mlg** [comment]
Whilst this is being worked on, what is the workaround please for successfully being able to run metric flow commands such as `mf list metrics` with a codebase.

I created a vanilla virtual environment where I installed just dbt-metricflow but running the `mf list metrics` commands complains about missing adapter. I guess `dbt-metricflow` is technically standalone but indirectly, it is not when you consider real world of what profiles.yml and artifact files look like. So then I went through a process of whack-a-mole installing dbt-adapters and then dbt-common etc. etc. to try and get to a place where I could run the command. Eventually, I installed everything together (incl dbt-core) but then you get the profobuf issue (`TypeError: Couldn't build proto file into descriptor pool: duplicate file name types.proto`) which is the one I assume updating dbt-metricflow's dependencies to not be incompatible with dbt 1.8 will solve.

But in the meantime, how can I get a stable environment?

**Comment by adamcunnington-mlg** [comment]
@plypaul please can you advise when a new version of dbt-metricflow will be released on pypi with this critical fix?

**Comment by plypaul** [comment]
@adamcunnington-mlg Sorry, missed your comment earlier. I tried a test run with a clean virtual environment, and things seemed to work with what's currently on master. Mind sharing the commands that you ran so I can reproduce it?

**Comment by adamcunnington-mlg** [comment]
@plypaul thank you - the problem can be reproduced by installing dbt-core and dbt-bigquery for 1.8 and then subsequently installing `dbt-metricflow` which will force a downgrade of `dbt-core` and then you'll run into a low-level Protobuf issue, basically caused by incompatibilities between the adapter's dependencies and dbt-core/dbt-metricflow.

You can get around this by doing `pip install dbt-metricflow[bigquery]` which will have the effect of downgrading both but the way I'd expect this to work is that dbt-metricflow's dependencies are more dynamic and controlled by my existing environment (dbt-core & dbt-bigquery).
