### ISSUE TITLE
There is no need to group by the dimensions of the primary key

### ISSUE THREAD

**Issue by lexluo09** [dbt-labs/metricflow#430]
**Describe the Feature**
There is no need to group by the dimensions of the primary key；

1. Now：

    SELECT
      primary_key
      , SUM(metric_a) 
      , SUM(metric_b) 
    FROM (
      SELECT
       *
      FROM 
      table_a
    ) table_a_0
    GROUP BY primary_key

2. Expect：

    SELECT
      primary_key
      , metric_a
      , metric_b
    FROM (
      SELECT
       *
      FROM 
      table_a
    ) table_a_0

**Would you like to contribute?**
Are you interested in building this feature?

**Anything Else?**

**Comment by tlento** [comment]
Hi @lexluo09 , thanks for filing! Apologies for the delay on all of these responses, we've been onboarding with dbt Labs and are just getting back into MetricFlow development!

Unfortunately, I'm not sure what you're referring to here. Is this the final outer query when we have multiple metrics selected in the query, requiring a join? If so, the final outer group by is necessary to consolidate rows where dimensions have NULL values. See https://github.com/dbt-labs/metricflow/pull/366 for context, although I would expect that to be MAX rather than SUM and also not showing up unless there's a join.

If you're referring to an extra group by elsewhere in the query plan, that is most likely a boundary case in our query optimization passes, and may represent an area where we can do further refinement. If you can provide a concrete repro case please do let us know, as we'd like to take a look and see if there's something we missed.

**Comment by Jstein77** [comment]
I'm gonna close this issue for now.
