### ISSUE TITLE
[SL-1438] [Feature] Request to relax the pin of MarkupSafe

### ISSUE THREAD

**Issue by ADraginda** [dbt-labs/metricflow#927]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The pinned version of `MarkupSafe`, 2.0.1, was released May 18, 2021 and causes problems when using `metricflow` within airflow because of a conflict of versions with the `apache-airflow` package.

The current comment in the [source code](https://github.com/dbt-labs/metricflow/blob/87d7061a6f464f83419e893aa22ee6a753fa2a6f/pyproject.toml#L29) shows

```
  "MarkupSafe==2.0.1", # pandas implicitly requires this version
``` 

But I cannot find any reason for this pin because of pandas and indeed, pandas installs just fine without the pin.

### Who will this benefit?

Anyone trying to use metricflow in an airflow python operator will run into this issue.

### Are you interested in contributing this feature?

I'd be happy to open a PR with the change

### Anything else?

This issue has been brought up before, please see https://github.com/dbt-labs/metricflow/issues/707
The [PR](https://github.com/dbt-labs/metricflow/pull/720/files) where the comment was added to the dependency pin

<sub>[SL-1438](https://linear.app/dbt-labs/issue/SL-1438/[feature]-request-to-relax-the-pin-of-markupsafe)</sub>

**Comment by Jstein77** [comment]
Thanks for adding this issue @ADraginda! Let me sync with the team on this one. I'll follow up once I have a more details!

**Comment by tlento** [comment]
We had some issues with runtime failures on installs that didn't explicitly pin the MarkupSafe version. This is likely because Pandas tries to do [a dynamic import off of jinja2](https://github.com/pandas-dev/pandas/blob/98e1d2f8cec1593bb8bc6a8dbdd164372286ea09/pandas/io/formats/style_render.py#L49) and something somewhere was broken somehow. 

Whatever that was looks like it was resolved, and clean installs without MarkupSafe are working as expected now. I'm going to remove the dependency altogether - we have no direct use for it.
